name: demo_max_way
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  yandex_mapkit: ^3.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.1
  firebase_core: ^2.24.2
  hive: ^2.2.3
  url_launcher: ^6.2.2
  flutter_share:
  firebase_auth: ^4.15.3
  pinput: ^3.0.1
  fluttertoast: ^8.2.4
  get_it: ^7.6.4
  floor: ^1.4.2
  maps_launcher: ^2.2.0
  flutter_holo_date_picker: ^1.1.3
#  flutter_datetime_picker: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  floor_generator: ^1.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  flutter pub add freezed_annotation
#  flutter pub add --dev build_runner
#  flutter pub add --dev freezed

#  dart run build_runner watch --delete-conflicting-outputs
