name: demo_max_way
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  yandex_mapkit: ^3.3.3
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.1
  hive: ^2.2.3
  url_launcher: ^6.1.12
  flutter_share:
  firebase_auth: ^4.8.0
  pinput: ^3.0.1
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  floor: ^1.4.2
  maps_launcher: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  flutter pub add freezed_annotation
#  flutter pub add --dev build_runner
#  flutter pub add --dev freezed

#  dart run build_runner watch --delete-conflicting-outputs
